name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: add protobuf
      run: sudo apt-get install protobuf-compiler libprotobuf-dev -y
      if: matrix.os == 'ubuntu-latest'
    - name: add protobuf
      run: brew install protobuf
      if: matrix.os == 'macos-latest'
    - name: create build
      run: mkdir build
    - name: configure
      run: cmake -DBUILD_TESTS=ON ..
      working-directory: ./build
    - name: build
      run: cmake --build . --target all
      working-directory: ./build
    - name: test
      run: ctest
      working-directory: ./build
